# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title               : AKai's Blog
tagline             : 'Data analysis articles'
description         : 'Sword, blood and egg.'
url                 : https://atoto9.github.io/
baseurl             : # 

author              : JK Lin
name                : 'JK Lin'


paginate            : 5

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version             : 0.1.0
github:
  repo:             https://github.com/atoto9/atoto9.github.io
sidebar_home_link:  true


