# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title               : AKai's Blog
tagline             : 'Data analysis articles'
description         : 'Sword, blood and egg.'
baseurl             : /

author              : JK Lin
name                : 'JK Lin'
url                 : https://atoto9.github.io/

paginate            : 5

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version             : 0.1.0
github_username     : atoto9


